import { getStore } from "@netlify/blobs";
const store=getStore("amdev-data"),C="amdev_session",TTL=604800;
const out=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{"content-type":"application/json",...h}});
const bad=(m,s=400)=>out({ok:false,error:m},s),now=()=>new Date().toISOString();
const b64=x=>btoa(String.fromCharCode(...new Uint8Array(x))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"");
const ub=x=>new Uint8Array([...atob(x.replace(/-/g,"+").replace(/_/g,"/")+"===".slice((x.length+3)%4))].map(c=>c.charCodeAt(0)));
async function mac(x){const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(process.env.AMDEV_SESSION_SECRET||""),{name:"HMAC",hash:"SHA-256"},false,["sign"]);return b64(await crypto.subtle.sign("HMAC",k,new TextEncoder().encode(x)))}
async function tok(role,id){const p=b64(new TextEncoder().encode(JSON.stringify({role,id,exp:Date.now()+TTL*1000})));return p+"."+await mac(p)}
async function sess(r){try{const m=(r.headers.get("cookie")||"").split(";").find(x=>x.trim().startsWith(C+"="));if(!m)return null;const [p,s]=decodeURIComponent(m.trim().slice(C.length+1)).split(".");if(s!==await mac(p))return null;const x=JSON.parse(new TextDecoder().decode(ub(p)));return x.exp>Date.now()?x:null}catch{return null}}
async function db(){return {...{clients:[],tasks:[],subscriptions:[],news:[],visits:[]},...((await store.get("db",{type:"json",consistency:"strong"}))||{})}}const save=x=>store.setJSON("db",x);
async function hash(p,s){s=s||b64(crypto.getRandomValues(new Uint8Array(16)));const k=await crypto.subtle.importKey("raw",new TextEncoder().encode(p),"PBKDF2",false,["deriveBits"]);const z=await crypto.subtle.deriveBits({name:"PBKDF2",salt:new TextEncoder().encode(s),iterations:120000,hash:"SHA-256"},k,256);return "pbkdf2:"+s+":"+b64(z)}
async function check(p,v){const a=String(v||"").split(":");return a.length===3&&(await hash(p,a[1]))===v}
const body=r=>r.json().catch(()=>({})),safe=x=>{const y={...x};delete y.passwordHash;return y};
async function clientLogin(d){const x=await db(),l=String(d.login||"").trim().toLowerCase(),c=x.clients.find(v=>v.login===l||v.email===l);if(!c||c.status==="blocked"||!(await check(String(d.password||""),c.passwordHash)))return bad("Неверный логин или пароль.",401);c.last_seen_at=now();x.visits.push({id:crypto.randomUUID(),client_id:c.id,visited_at:now()});await save(x);return out({ok:true},200,{"set-cookie":C+"="+encodeURIComponent(await tok("client",c.id))+"; Max-Age="+TTL+"; Path=/; HttpOnly; SameSite=Lax; Secure"})}
async function adminLogin(d){if(!process.env.AMDEV_ADMIN_PASSWORD)return bad("AMDEV_ADMIN_PASSWORD не настроен.",503);if(String(d.login||"").trim().toLowerCase()!==(process.env.AMDEV_ADMIN_LOGIN||"admin").toLowerCase()||String(d.password||"")!==process.env.AMDEV_ADMIN_PASSWORD)return bad("Неверный логин или пароль.",401);return out({ok:true},200,{"set-cookie":C+"="+encodeURIComponent(await tok("admin",""))+"; Max-Age="+TTL+"; Path=/; HttpOnly; SameSite=Lax; Secure"})}
async function auth(r,role){const s=await sess(r);return s&&s.role===role?s:null}
export default async function(r){try{const a=new URL(r.url).searchParams.get("action"),d=await body(r);if(r.method==="POST"&&a==="client-login")return clientLogin(d);if(r.method==="POST"&&a==="admin-login")return adminLogin(d);if(r.method==="POST"&&a==="logout")return out({ok:true},200,{"set-cookie":C+"=; Max-Age=0; Path=/; HttpOnly; SameSite=Lax; Secure"});if(r.method==="GET"&&a==="client-me"){const s=await auth(r,"client");if(!s)return bad("Сессия истекла.",401);const x=await db(),c=x.clients.find(v=>v.id===s.id);if(!c)return bad("Сессия истекла.",401);c.last_seen_at=now();await save(x);return out({ok:true,client:safe(c),tasks:x.tasks.filter(t=>t.client_id===c.id),subscription:x.subscriptions.find(v=>v.client_id===c.id)||null,news:x.news.slice(-3).reverse()})}if(r.method==="GET"&&a==="admin-data"){if(!await auth(r,"admin"))return bad("Нет доступа.",401);const x=await db();return out({ok:true,clients:x.clients.map(safe),tasks:x.tasks,subscriptions:x.subscriptions,news:x.news,visits:x.visits})}if(r.method==="POST"&&a.startsWith("admin-")){if(!await auth(r,"admin"))return bad("Нет доступа.",401);const x=await db();if(a==="admin-client-save"){let c=x.clients.find(v=>v.id===d.id);if(!c){c={id:crypto.randomUUID(),created_at:now(),passwordHash:""};x.clients.push(c)}Object.assign(c,{login:String(d.login||"").trim().toLowerCase(),email:String(d.email||"").trim(),display_name:String(d.display_name||d.login).trim(),site_url:String(d.site_url||"").trim(),contact:String(d.contact||"").trim(),project_status:String(d.project_status||"").trim(),status:d.status==="blocked"?"blocked":"active"});if(d.password)c.passwordHash=await hash(String(d.password));if(!c.passwordHash)return bad("Для нового клиента нужен пароль.",422)}else if(a==="admin-task-save"){let t=x.tasks.find(v=>v.id===d.id);if(!t){t={id:crypto.randomUUID(),created_at:now()};x.tasks.push(t)}Object.assign(t,{client_id:d.client_id,title:String(d.title||"").trim(),status:d.status||"waiting",updated_at:now()})}else if(a==="admin-sub-save"){let s=x.subscriptions.find(v=>v.client_id===d.client_id);if(!s){s={id:crypto.randomUUID(),client_id:d.client_id};x.subscriptions.push(s)}Object.assign(s,d)}else if(a==="admin-news-save"){let n=x.news.find(v=>v.id===d.id);if(!n){n={id:crypto.randomUUID(),created_at:now()};x.news.push(n)}Object.assign(n,{title:d.title,body:d.body})}else if(a==="admin-client-delete"){x.clients=x.clients.filter(v=>v.id!==d.id);x.tasks=x.tasks.filter(v=>v.client_id!==d.id);x.subscriptions=x.subscriptions.filter(v=>v.client_id!==d.id)}else if(a==="admin-task-delete")x.tasks=x.tasks.filter(v=>v.id!==d.id);else if(a==="admin-news-delete")x.news=x.news.filter(v=>v.id!==d.id);await save(x);return out({ok:true})}return bad("Unknown API action.",404)}catch(e){console.error(e);return bad("Внутренняя ошибка сервера.",500)}}